@startuml

title __UTILS's Class Diagram__\n

  namespace com.ustc.location {
    namespace utils {
      class com.ustc.location.utils.FileUtils {
          {static} - FAILED : int
          {static} - SUCCESS : int
          - context : Context
          - errorStr : String
          - handler : Handler
          {static} - instance : FileUtils
          - isSuccess : boolean
          + copyAssetsToSD()
          {static} + fileIsExists()
          {static} + getInstance()
          + setFileOperateCallback()
          - FileUtils()
          - copyAssetsToDst()
      }
    }
  }
  

  namespace com.ustc.location {
    namespace utils {
      interface com.ustc.location.utils.FileUtils.FileOperateCallback {
          {abstract} + onFailed()
          {abstract} + onSuccess()
      }
    }
  }
  

  namespace com.ustc.location {
    namespace utils {
      class com.ustc.location.utils.SaveUtils {
          {static} + saveBitmap()
          {static} + saveMapViewScreen()
      }
    }
  }
  

  namespace com.ustc.location {
    namespace utils {
      class com.ustc.location.utils.SymbolUtils {
          {static} - areaCount : int[]
          {static} - colorArray : String[]
          {static} - fillSymbols : FillSymbol[]
          {static} - peopleCount : int[]
          {static} + getSymbolFromArea()
          {static} + getSymbolFromPopulation()
          {static} - getIndexFromCount()
      }
    }
  }
  

  namespace com.ustc.location {
    namespace utils {
      class com.ustc.location.utils.Uri2PathUtil {
          {static} + getDataColumn()
          {static} + getRealPathFromUri()
          {static} + isDownloadsDocument()
          {static} + isExternalStorageDocument()
          {static} + isMediaDocument()
          {static} - getRealPathFromUri_AboveApi19()
          {static} - getRealPathFromUri_Api11To18()
          {static} - getRealPathFromUri_BelowApi11()
      }
    }
  }
  

  com.ustc.location.utils.FileUtils o-- com.ustc.location.utils.FileUtils.FileOperateCallback : callback
  com.ustc.location.utils.FileUtils +-down- com.ustc.location.utils.FileUtils.FileOperateCallback


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
