@startuml

title __SCAN's Class Diagram__\n

  namespace com.clj.fastble {
    namespace scan {
      abstract class com.clj.fastble.scan.BleScanPresenter {
          - mBleDeviceList : List<BleDevice>
          - mDeviceMac : String
          - mDeviceNames : String[]
          - mFuzzy : boolean
          - mHandler : Handler
          - mHandlerThread : HandlerThread
          - mHandling : boolean
          - mMainHandler : Handler
          - mNeedConnect : boolean
          - mScanTimeout : long
          + getBleScanPresenterImp()
          + ismNeedConnect()
          + notifyScanStarted()
          + notifyScanStopped()
          + onLeScan()
          {abstract} + onLeScan()
          {abstract} + onScanFinished()
          {abstract} + onScanStarted()
          {abstract} + onScanning()
          + prepare()
          + removeHandlerMsg()
          - checkDevice()
          - correctDeviceAndNextStep()
          - handleResult()
      }
    }
  }
  

  namespace com.clj.fastble {
    namespace scan {
      class com.clj.fastble.scan.BleScanPresenter.ScanHandler {
          - mBleScanPresenter : WeakReference<BleScanPresenter>
          + handleMessage()
          ~ ScanHandler()
      }
    }
  }
  

  namespace com.clj.fastble {
    namespace scan {
      class com.clj.fastble.scan.BleScanRuleConfig {
          - mAutoConnect : boolean
          - mDeviceMac : String
          - mDeviceNames : String[]
          - mFuzzy : boolean
          - mScanTimeOut : long
          - mServiceUuids : UUID[]
          + getDeviceMac()
          + getDeviceNames()
          + getScanTimeOut()
          + getServiceUuids()
          + isAutoConnect()
          + isFuzzy()
      }
    }
  }
  

  namespace com.clj.fastble {
    namespace scan {
      class com.clj.fastble.scan.BleScanRuleConfig.Builder {
          - mAutoConnect : boolean
          - mDeviceMac : String
          - mDeviceNames : String[]
          - mFuzzy : boolean
          - mServiceUuids : UUID[]
          - mTimeOut : long
          + build()
          + setAutoConnect()
          + setDeviceMac()
          + setDeviceName()
          + setScanTimeOut()
          + setServiceUuids()
          ~ applyConfig()
      }
    }
  }
  

  namespace com.clj.fastble {
    namespace scan {
      class com.clj.fastble.scan.BleScanner {
          {static} + getInstance()
          + getScanState()
          + scan()
          + scanAndConnect()
          + stopLeScan()
          - startLeScan()
      }
    }
  }
  

  namespace com.clj.fastble {
    namespace scan {
      class com.clj.fastble.scan.BleScanner.BleScannerHolder {
          {static} - sBleScanner : BleScanner
      }
    }
  }
  

  com.clj.fastble.scan.BleScanPresenter .up.|> android.bluetooth.BluetoothAdapter.LeScanCallback
  com.clj.fastble.scan.BleScanPresenter o-- com.clj.fastble.callback.BleScanPresenterImp : mBleScanPresenterImp
  com.clj.fastble.scan.BleScanPresenter +-down- com.clj.fastble.scan.BleScanPresenter.ScanHandler
  com.clj.fastble.scan.BleScanPresenter.ScanHandler -up-|> android.os.Handler
  com.clj.fastble.scan.BleScanRuleConfig +-down- com.clj.fastble.scan.BleScanRuleConfig.Builder
  com.clj.fastble.scan.BleScanner o-- com.clj.fastble.scan.BleScanPresenter : mBleScanPresenter
  com.clj.fastble.scan.BleScanner o-- com.clj.fastble.data.BleScanState : mBleScanState
  com.clj.fastble.scan.BleScanner +-down- com.clj.fastble.scan.BleScanner.BleScannerHolder


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
