@startuml

title __CALLBACK's Class Diagram__\n

  namespace com.clj.fastble {
    namespace callback {
      abstract class com.clj.fastble.callback.BleBaseCallback {
          - handler : Handler
          - key : String
          + getHandler()
          + getKey()
          + setHandler()
          + setKey()
      }
    }
  }
  

  namespace com.clj.fastble {
    namespace callback {
      abstract class com.clj.fastble.callback.BleGattCallback {
          {abstract} + onConnectFail()
          {abstract} + onConnectSuccess()
          {abstract} + onDisConnected()
          {abstract} + onStartConnect()
      }
    }
  }
  

  namespace com.clj.fastble {
    namespace callback {
      abstract class com.clj.fastble.callback.BleIndicateCallback {
          {abstract} + onCharacteristicChanged()
          {abstract} + onIndicateFailure()
          {abstract} + onIndicateSuccess()
      }
    }
  }
  

  namespace com.clj.fastble {
    namespace callback {
      abstract class com.clj.fastble.callback.BleMtuChangedCallback {
          {abstract} + onMtuChanged()
          {abstract} + onSetMTUFailure()
      }
    }
  }
  

  namespace com.clj.fastble {
    namespace callback {
      abstract class com.clj.fastble.callback.BleNotifyCallback {
          {abstract} + onCharacteristicChanged()
          {abstract} + onNotifyFailure()
          {abstract} + onNotifySuccess()
      }
    }
  }
  

  namespace com.clj.fastble {
    namespace callback {
      abstract class com.clj.fastble.callback.BleReadCallback {
          {abstract} + onReadFailure()
          {abstract} + onReadSuccess()
      }
    }
  }
  

  namespace com.clj.fastble {
    namespace callback {
      abstract class com.clj.fastble.callback.BleRssiCallback {
          {abstract} + onRssiFailure()
          {abstract} + onRssiSuccess()
      }
    }
  }
  

  namespace com.clj.fastble {
    namespace callback {
      abstract class com.clj.fastble.callback.BleScanAndConnectCallback {
          + onLeScan()
          {abstract} + onScanFinished()
      }
    }
  }
  

  namespace com.clj.fastble {
    namespace callback {
      abstract class com.clj.fastble.callback.BleScanCallback {
          + onLeScan()
          {abstract} + onScanFinished()
      }
    }
  }
  

  namespace com.clj.fastble {
    namespace callback {
      interface com.clj.fastble.callback.BleScanPresenterImp {
          {abstract} + onScanStarted()
          {abstract} + onScanning()
      }
    }
  }
  

  namespace com.clj.fastble {
    namespace callback {
      abstract class com.clj.fastble.callback.BleWriteCallback {
          {abstract} + onWriteFailure()
          {abstract} + onWriteSuccess()
      }
    }
  }
  

  com.clj.fastble.callback.BleGattCallback -up-|> android.bluetooth.BluetoothGattCallback
  com.clj.fastble.callback.BleIndicateCallback -up-|> com.clj.fastble.callback.BleBaseCallback
  com.clj.fastble.callback.BleMtuChangedCallback -up-|> com.clj.fastble.callback.BleBaseCallback
  com.clj.fastble.callback.BleNotifyCallback -up-|> com.clj.fastble.callback.BleBaseCallback
  com.clj.fastble.callback.BleReadCallback -up-|> com.clj.fastble.callback.BleBaseCallback
  com.clj.fastble.callback.BleRssiCallback -up-|> com.clj.fastble.callback.BleBaseCallback
  com.clj.fastble.callback.BleScanAndConnectCallback .up.|> com.clj.fastble.callback.BleScanPresenterImp
  com.clj.fastble.callback.BleScanAndConnectCallback -up-|> com.clj.fastble.callback.BleGattCallback
  com.clj.fastble.callback.BleScanCallback .up.|> com.clj.fastble.callback.BleScanPresenterImp
  com.clj.fastble.callback.BleWriteCallback -up-|> com.clj.fastble.callback.BleBaseCallback


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
