@startuml

title __EXCEPTION's Class Diagram__\n

  namespace com.clj.fastble {
    namespace exception {
      abstract class com.clj.fastble.exception.BleException {
          {static} + ERROR_CODE_GATT : int
          {static} + ERROR_CODE_OTHER : int
          {static} + ERROR_CODE_TIMEOUT : int
          - code : int
          - description : String
          {static} - serialVersionUID : long
          + BleException()
          + getCode()
          + getDescription()
          + setCode()
          + setDescription()
          + toString()
      }
    }
  }
  

  namespace com.clj.fastble {
    namespace exception {
      class com.clj.fastble.exception.ConnectException {
          - bluetoothGatt : BluetoothGatt
          - gattStatus : int
          + ConnectException()
          + getBluetoothGatt()
          + getGattStatus()
          + setBluetoothGatt()
          + setGattStatus()
          + toString()
      }
    }
  }
  

  namespace com.clj.fastble {
    namespace exception {
      class com.clj.fastble.exception.GattException {
          - gattStatus : int
          + GattException()
          + getGattStatus()
          + setGattStatus()
          + toString()
      }
    }
  }
  

  namespace com.clj.fastble {
    namespace exception {
      class com.clj.fastble.exception.OtherException {
          + OtherException()
      }
    }
  }
  

  namespace com.clj.fastble {
    namespace exception {
      class com.clj.fastble.exception.TimeoutException {
          + TimeoutException()
      }
    }
  }
  

  com.clj.fastble.exception.BleException .up.|> java.io.Serializable
  com.clj.fastble.exception.ConnectException -up-|> com.clj.fastble.exception.BleException
  com.clj.fastble.exception.GattException -up-|> com.clj.fastble.exception.BleException
  com.clj.fastble.exception.OtherException -up-|> com.clj.fastble.exception.BleException
  com.clj.fastble.exception.TimeoutException -up-|> com.clj.fastble.exception.BleException


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
